/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */




//import com.sun.prism.paint.Color; 
import javax.swing.JOptionPane;
import java.awt.Dimension;  // To set dimension of JOP
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author sony
 */
public class LogIn extends javax.swing.JFrame {
String EMAIL,PASS,GENDER;ResultSet rs=null;final JDialog d=new JDialog();       //Global variables
   
    
    public LogIn() 
{   initComponents();

    Label_bigimg.setVisible(true);
    Label_tyfor.setVisible(false);
    Label_wehope.setVisible(false);
    Label_ty.setVisible(false);
    Label_ty1.setVisible(false);                                                //To not show the password in jtextfield 
    TF_ShowPass.setVisible(false);

                                       //To disable all error lables of * types. 
    e1.setVisible(false); e2.setVisible(false); e3.setVisible(false); e4.setVisible(false); e5.setVisible(false);e6.setVisible(false);
        Print_loading();
}
    
    public LogIn(int a) 
{   initComponents();
    
    Label_ty.setVisible(false);
    Label_ty1.setVisible(false);
    TF_ShowPass.setVisible(false);
    
    if(a==1)                                                                    // a says that user has come from other page.
        Label_ty.setVisible(true);
    else 
        Label_ty1.setVisible(true);
    
    Label_tyfor.setVisible(true);
    Label_wehope.setVisible(true);
    Label_bigimg.setVisible(false);
                                           //To disable all error lables of * types. 
   
    e1.setVisible(false); e2.setVisible(false); e3.setVisible(false); e4.setVisible(false); e5.setVisible(false);e6.setVisible(false);
        Print_loading();
}

    // METHOD
    public void Print_loading()
{
        
        JPanel p1 = new JPanel(new GridBagLayout());
                JLabel jLabel1=new JLabel();
                jLabel1.setIcon(new ImageIcon("src\\images\\Loading_gif.gif"));
                p1.add( jLabel1,new GridBagConstraints());
                
                d.getContentPane().add(p1);
                d.setSize(251,246);

                d.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
                d.setModal(true);
                d.setUndecorated(true);
       
                d.setLocationRelativeTo(null);
}
    
                // Method to change email into valid TABLE name for sql.   
    String ChangeToValidTableName(String a)
{
    String validname=""; 
        for(int i=0;i<a.length();i++)
            {
                char k=0;
                k=a.charAt(i);
                if(k=='.' || k=='@');
                else
                    validname+=k;

            }
        return validname;
}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor. ///\\\
     * 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TF_LogIn_Email = new javax.swing.JTextField();
        Button_LogIn = new javax.swing.JButton();
        PF_LogIn_pass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Aboutus_Button = new javax.swing.JButton();
        Help_Label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fnamelable = new javax.swing.JLabel();
        reemaillable = new javax.swing.JLabel();
        snamelable = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        newpasslable = new javax.swing.JLabel();
        e4 = new javax.swing.JLabel();
        newemaillable = new javax.swing.JLabel();
        TF_ShowPass = new javax.swing.JTextField();
        TF_Sname = new javax.swing.JTextField();
        TF_Fname = new javax.swing.JTextField();
        TF_NewEmail = new javax.swing.JTextField();
        TF_ReEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        daycb = new javax.swing.JComboBox();
        yearcb = new javax.swing.JComboBox();
        monthcb = new javax.swing.JComboBox();
        RB_Male = new javax.swing.JRadioButton();
        RB_Female = new javax.swing.JRadioButton();
        Label_TandC = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Button_createaccount = new javax.swing.JButton();
        e2 = new javax.swing.JLabel();
        e3 = new javax.swing.JLabel();
        e5 = new javax.swing.JLabel();
        e6 = new javax.swing.JLabel();
        e1 = new javax.swing.JLabel();
        PF_NewPass = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Label_tyfor = new javax.swing.JLabel();
        Label_wehope = new javax.swing.JLabel();
        Label_ty1 = new javax.swing.JLabel();
        Label_ty = new javax.swing.JLabel();
        Label_bigimg = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LogIn");
        setMaximumSize(new java.awt.Dimension(1025, 675));
        setMinimumSize(new java.awt.Dimension(1010, 651));
        setPreferredSize(new java.awt.Dimension(999, 651));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");

        TF_LogIn_Email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TF_LogIn_EmailFocusLost(evt);
            }
        });

        Button_LogIn.setBackground(new java.awt.Color(0, 51, 255));
        Button_LogIn.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Button_LogIn.setForeground(new java.awt.Color(255, 255, 255));
        Button_LogIn.setText("Log In");
        Button_LogIn.setToolTipText("Log In");
        Button_LogIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_LogInActionPerformed(evt);
            }
        });

        PF_LogIn_pass.setEchoChar('\u2022');
        PF_LogIn_pass.setName(""); // NOI18N
        PF_LogIn_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PF_LogIn_passFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tekton Pro", 0, 75)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/front.gif"))); // NOI18N
        jLabel5.setToolTipText("asapp v1.0.0");

        jLabel16.setBackground(new java.awt.Color(204, 255, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("C O N N E C T      W I T H      Y O U R      L O V E D      O N C E ");

        jLabel15.setFont(new java.awt.Font("SimHei", 1, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("sapp");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_LogIn_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PF_LogIn_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(Button_LogIn)))
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TF_LogIn_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_LogIn)
                            .addComponent(PF_LogIn_pass))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-1, 0, 1030, 120);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("B H A R A T           S H R I V A S T A V A ' S             P R O D U C T I O N             A S A P P         © 2 0 1 6");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(270, 570, 421, 10);

        Aboutus_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/about.jpg"))); // NOI18N
        Aboutus_Button.setToolTipText("About Us");
        Aboutus_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Aboutus_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aboutus_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Aboutus_Button);
        Aboutus_Button.setBounds(10, 130, 90, 50);

        Help_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help1.png"))); // NOI18N
        Help_Label.setToolTipText("Need Help ?");
        Help_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Help_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Help_LabelMouseClicked(evt);
            }
        });
        getContentPane().add(Help_Label);
        Help_Label.setBounds(0, 590, 70, 30);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setText("Create an account");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(560, 120, 310, 60);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel4.setText("it's free and always will be.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(570, 170, 160, 15);

        fnamelable.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        fnamelable.setForeground(new java.awt.Color(102, 102, 102));
        fnamelable.setText("First name");
        getContentPane().add(fnamelable);
        fnamelable.setBounds(580, 210, 80, 30);

        reemaillable.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        reemaillable.setForeground(new java.awt.Color(102, 102, 102));
        reemaillable.setText("Re-enter email address");
        getContentPane().add(reemaillable);
        reemaillable.setBounds(580, 290, 150, 30);

        snamelable.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        snamelable.setForeground(new java.awt.Color(102, 102, 102));
        snamelable.setText("Surname");
        getContentPane().add(snamelable);
        snamelable.setBounds(760, 210, 80, 30);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eye.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel17MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel17MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel17);
        jLabel17.setBounds(900, 330, 15, 30);

        newpasslable.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        newpasslable.setForeground(new java.awt.Color(102, 102, 102));
        newpasslable.setText("New password");
        getContentPane().add(newpasslable);
        newpasslable.setBounds(580, 330, 100, 30);

        e4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        e4.setForeground(new java.awt.Color(255, 51, 51));
        e4.setText("*");
        getContentPane().add(e4);
        e4.setBounds(560, 300, 10, 15);

        newemaillable.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        newemaillable.setForeground(new java.awt.Color(102, 102, 102));
        newemaillable.setText("Email address");
        getContentPane().add(newemaillable);
        newemaillable.setBounds(580, 250, 90, 30);
        getContentPane().add(TF_ShowPass);
        TF_ShowPass.setBounds(570, 330, 350, 30);

        TF_Sname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TF_SnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TF_SnameFocusLost(evt);
            }
        });
        TF_Sname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TF_SnameKeyTyped(evt);
            }
        });
        getContentPane().add(TF_Sname);
        TF_Sname.setBounds(750, 210, 170, 30);

        TF_Fname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TF_FnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TF_FnameFocusLost(evt);
            }
        });
        TF_Fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TF_FnameKeyTyped(evt);
            }
        });
        getContentPane().add(TF_Fname);
        TF_Fname.setBounds(570, 210, 170, 30);

        TF_NewEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TF_NewEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TF_NewEmailFocusLost(evt);
            }
        });
        getContentPane().add(TF_NewEmail);
        TF_NewEmail.setBounds(570, 250, 350, 30);

        TF_ReEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TF_ReEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TF_ReEmailFocusLost(evt);
            }
        });
        getContentPane().add(TF_ReEmail);
        TF_ReEmail.setBounds(570, 290, 350, 30);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel9.setText("Birthday");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(570, 370, 70, 18);

        daycb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        daycb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(daycb);
        daycb.setBounds(570, 400, 60, 30);

        yearcb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007" }));
        yearcb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(yearcb);
        yearcb.setBounds(720, 400, 70, 30);

        monthcb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        monthcb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(monthcb);
        monthcb.setBounds(640, 400, 70, 30);

        buttonGroup1.add(RB_Male);
        RB_Male.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        RB_Male.setText("Male");
        RB_Male.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(RB_Male);
        RB_Male.setBounds(650, 440, 55, 25);

        buttonGroup1.add(RB_Female);
        RB_Female.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RB_Female.setText("Female");
        RB_Female.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(RB_Female);
        RB_Female.setBounds(570, 440, 70, 25);

        Label_TandC.setFont(new java.awt.Font("Trebuchet MS", 0, 9)); // NOI18N
        Label_TandC.setForeground(new java.awt.Color(51, 51, 51));
        Label_TandC.setText("Terms and Conditions.");
        Label_TandC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Label_TandC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_TandCMouseClicked(evt);
            }
        });
        getContentPane().add(Label_TandC);
        Label_TandC.setBounds(570, 480, 110, 11);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 9)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("By clicking on Create an account you agree to our ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(570, 470, 260, 11);

        Button_createaccount.setBackground(new java.awt.Color(0, 102, 0));
        Button_createaccount.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Button_createaccount.setForeground(new java.awt.Color(255, 255, 255));
        Button_createaccount.setText("Create an account");
        Button_createaccount.setToolTipText("Create an account.");
        Button_createaccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_createaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_createaccountActionPerformed(evt);
            }
        });
        getContentPane().add(Button_createaccount);
        Button_createaccount.setBounds(570, 500, 200, 40);

        e2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        e2.setForeground(new java.awt.Color(255, 51, 51));
        e2.setText("*");
        getContentPane().add(e2);
        e2.setBounds(740, 220, 10, 15);

        e3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        e3.setForeground(new java.awt.Color(255, 51, 51));
        e3.setText("*");
        getContentPane().add(e3);
        e3.setBounds(560, 260, 10, 15);

        e5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        e5.setForeground(new java.awt.Color(255, 51, 51));
        e5.setText("*");
        getContentPane().add(e5);
        e5.setBounds(560, 340, 10, 15);

        e6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        e6.setForeground(new java.awt.Color(255, 51, 51));
        e6.setText("*");
        getContentPane().add(e6);
        e6.setBounds(560, 450, 10, 15);

        e1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        e1.setForeground(new java.awt.Color(255, 51, 51));
        e1.setText("*");
        getContentPane().add(e1);
        e1.setBounds(560, 220, 10, 15);

        PF_NewPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PF_NewPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PF_NewPassFocusLost(evt);
            }
        });
        getContentPane().add(PF_NewPass);
        PF_NewPass.setBounds(570, 330, 350, 30);

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("in your life.");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(70, 210, 280, 18);

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("ASAPP helps you connect with the people ");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(70, 190, 280, 18);

        Label_tyfor.setFont(new java.awt.Font("Trebuchet MS", 0, 10)); // NOI18N
        Label_tyfor.setForeground(new java.awt.Color(102, 102, 102));
        Label_tyfor.setText("Thanks for stopping by!");
        getContentPane().add(Label_tyfor);
        Label_tyfor.setBounds(150, 120, 240, 22);

        Label_wehope.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        Label_wehope.setForeground(new java.awt.Color(153, 153, 153));
        Label_wehope.setText("We hope to see you again soon.");
        getContentPane().add(Label_wehope);
        Label_wehope.setBounds(130, 140, 160, 14);

        Label_ty1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ty2.png"))); // NOI18N
        getContentPane().add(Label_ty1);
        Label_ty1.setBounds(70, 260, 310, 280);

        Label_ty.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ty1.png"))); // NOI18N
        getContentPane().add(Label_ty);
        Label_ty.setBounds(150, 230, 300, 310);

        Label_bigimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Connected-Workplace.png"))); // NOI18N
        getContentPane().add(Label_bigimg);
        Label_bigimg.setBounds(100, 230, 440, 310);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(570, 490, 90, 10);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/silver-light-blue-wave-abstract-backgrounds-powerpoint-1024x725.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 120, 1010, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents
// LOG IN BUTTON
    private void Button_LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_LogInActionPerformed
 
                                                                                // It takes email from direct login mail TF.
String EMAIL=TF_LogIn_Email.getText();
                                                                                // It takes pass from direct pass PF.
String PASS=new String(PF_LogIn_pass.getPassword());

                                                                                //If both the fields are empty.
    if(EMAIL.isEmpty() || PASS.isEmpty())
    {
        JOptionPane.showMessageDialog(null,"Please Check the details you have Typed.");
    }
    else                                                                        // If details are correct
    {            
        Thread t = new Thread()
        {
            public  void run()
            {
            // TASK BEGIN 
       
                try{            
                        boolean error1=false;
                        String DNAME=ChangeToValidTableName(EMAIL);          // change to TABLE name for further use
                    // BACK END STARTs
                        Class.forName(Class_Setting.DRIVER_MANAGER);
                        Connection con=DriverManager.getConnection(Class_Setting.URL+Class_Setting.DATABASE_NAME,Class_Setting.USERNAME,Class_Setting.PASSWORD);
                        Statement stmt=con.createStatement();

                        String query="Select count(*) from profile_"+DNAME+";"; // open Portion of user (given email)

                            try{
                                    stmt.executeQuery(query);  
                                }
                            catch(Exception e)
                                    {   error1=true;
                                            JOptionPane.showMessageDialog(null,"No such Account Exist.\n "
                                                            + "Please create an account first. \n"
                                                            + "Make sure you are connected with you Network Connection.");
                                    }
                        if(!error1)
                        {
                            query="Select * from profile_"+DNAME+";"; 
                            rs=stmt.executeQuery(query);
                            rs.last();
                        // to take out real values from profile table of user Table
                            String REALEMAIL=rs.getString("email"); 
                            String REALPASS=rs.getString("pass");
                            String FNAME=rs.getString("name");                  // FNAME= First Name of user
                            GENDER=rs.getString("GENDER");
                    // Back end off
                            GENDER=GENDER.substring(0,1);                       // it is to take M or F
                            System.out.println(REALEMAIL+REALPASS);             // printing to confirm the values


                            if(EMAIL.equals(REALEMAIL) && PASS.equals(REALPASS)) // if user type the correct email and pass
                            {
                                new chatpage(EMAIL,PASS,GENDER,FNAME).setVisible(true);dispose(); // chatpage or account log In

                            }
                            else
                            JOptionPane.showMessageDialog(rootPane, "Use correct email and password.");
                        }                  

                    }
                catch(Exception er)
                    {
                        JOptionPane.showMessageDialog(rootPane, "Unable to connect \n check your network and try again.");System.out.print(er.getMessage());
                    }
            // TASK END
        SwingUtilities.invokeLater(new Runnable()
                    {                                                               //do swing work on EDT
                      
                        public void run()
                        {
                        d.dispose();
                        }
                    }                       );
            }
        };
                t.start();
               d.setVisible(true); 
  
    }
      
    }//GEN-LAST:event_Button_LogInActionPerformed
// ABOUT US BUTTON
    private void Aboutus_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aboutus_ButtonActionPerformed
Class_Website.GoToAsappOfficial();   
    }//GEN-LAST:event_Aboutus_ButtonActionPerformed

    private void Help_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Help_LabelMouseClicked
Class_Website.GoToAsappOfficial();
    }//GEN-LAST:event_Help_LabelMouseClicked
// First name TF
    private void TF_FnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TF_FnameFocusGained
fnamelable.setVisible(false);        
    }//GEN-LAST:event_TF_FnameFocusGained
// Sur name  TF
    private void TF_SnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TF_SnameFocusGained
snamelable.setVisible(false);       
    }//GEN-LAST:event_TF_SnameFocusGained
// sign up Email TF
    private void TF_NewEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TF_NewEmailFocusGained
newemaillable.setVisible(false);        
    }//GEN-LAST:event_TF_NewEmailFocusGained
// sign re email TF
    private void TF_ReEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TF_ReEmailFocusGained
reemaillable.setVisible(false);    
    }//GEN-LAST:event_TF_ReEmailFocusGained

    private void TF_FnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TF_FnameFocusLost
TF_Fname.setText(TF_Fname.getText().trim());     
if(TF_Fname.getText().isEmpty())
    fnamelable.setVisible(true);
    }//GEN-LAST:event_TF_FnameFocusLost

    private void TF_SnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TF_SnameFocusLost
TF_Sname.setText(TF_Sname.getText().trim());  
if(TF_Sname.getText().isEmpty())
    snamelable.setVisible(true);
    }//GEN-LAST:event_TF_SnameFocusLost

    private void TF_NewEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TF_NewEmailFocusLost
TF_NewEmail.setText(TF_NewEmail.getText().trim());  
if(TF_NewEmail.getText().isEmpty())
    newemaillable.setVisible(true);
    }//GEN-LAST:event_TF_NewEmailFocusLost

    private void TF_ReEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TF_ReEmailFocusLost
TF_ReEmail.setText(TF_ReEmail.getText().trim());    
if(TF_ReEmail.getText().isEmpty())
    reemaillable.setVisible(true);
    }//GEN-LAST:event_TF_ReEmailFocusLost

    private void TF_LogIn_EmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TF_LogIn_EmailFocusLost
 TF_LogIn_Email.setText(TF_LogIn_Email.getText().trim());         
    }//GEN-LAST:event_TF_LogIn_EmailFocusLost

    private void PF_LogIn_passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PF_LogIn_passFocusLost
PF_LogIn_pass.setText(PF_LogIn_pass.getText().trim());         
    }//GEN-LAST:event_PF_LogIn_passFocusLost

// Create ACCOUNT BUTTON (GREEN)
    private void Button_createaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_createaccountActionPerformed
// To take the details aq. to user typed   

 String FNAME=TF_Fname.getText();
 String SNAME=TF_Sname.getText();
 String NEWEMAIL=TF_NewEmail.getText();
 String REEMAIL=TF_ReEmail.getText();
 String NEWPASS=new String(PF_NewPass.getPassword());
                                            // default values of DOB 

    String gender="0";                      // default values of gender =0 , which means no gender has been selected.
    if(RB_Female.isSelected())   {gender="F";GENDER="F";}
    else if(RB_Male.isSelected()){gender="M";GENDER="M";}

                if(FNAME.isEmpty())                                             // if First name is not entered.
                {   e1.setVisible(true);TF_Fname.grabFocus();
                    e2.setVisible(false);e3.setVisible(false);e5.setVisible(false);e4.setVisible(false);e6.setVisible(false);}
                else if(SNAME.isEmpty())                                        // if sur name is not entered.
                {   e2.setVisible(true);TF_Sname.grabFocus();
                    e1.setVisible(false);e3.setVisible(false);e5.setVisible(false);e4.setVisible(false);e6.setVisible(false);
                }        
                else if(NEWEMAIL.isEmpty())                                     // if email not entered.
                {   e3.setVisible(true); TF_NewEmail.grabFocus();
                    e1.setVisible(false);e2.setVisible(false);e5.setVisible(false);e4.setVisible(false);e6.setVisible(false);
                }
                else if(REEMAIL.isEmpty() || !NEWEMAIL.equals(REEMAIL))         // if email and re email is not same.
                {   e4.setVisible(true);TF_ReEmail.grabFocus(); 
                    e1.setVisible(false);e2.setVisible(false);e3.setVisible(false);e5.setVisible(false);e6.setVisible(false);
                }
                else if(NEWPASS.isEmpty())                                      // is pass is not entered.
                {   e5.setVisible(true);PF_NewPass.grabFocus();
                    e1.setVisible(false);e2.setVisible(false);e3.setVisible(false);e4.setVisible(false);e6.setVisible(false);
                }
                else if(NEWPASS.length()<8)                                     // is pass is not entered.
                {   JOptionPane.showMessageDialog(null,"Password must contain minimum 8 charater.");
                    e5.setVisible(true);PF_NewPass.grabFocus();
                    e1.setVisible(false);e2.setVisible(false);e3.setVisible(false);e4.setVisible(false);e6.setVisible(false);
                }
                else if(gender.equals("0"))                                    // if gender is not selected.
                {   e6.setVisible(true); 
                    e1.setVisible(false);e2.setVisible(false);e3.setVisible(false);e5.setVisible(false);e4.setVisible(false);}
                else 
                {   
                    Thread t = new Thread()
                    {
                       public  void run()
                        {
                        // TASK BEGIN 
       
                            boolean error_dob=false;
                            int DAY=-1,MONTH=-1,YEAR=-1;
                            e6.setVisible(false); 

                         try{                                                   // to take the DOB of user
                             DAY=Integer.parseInt((String) daycb.getSelectedItem());
                             MONTH=Integer.parseInt((String) monthcb.getSelectedItem());
                             YEAR=Integer.parseInt((String) yearcb.getSelectedItem());
                            }
                         catch(Exception e)
                            { 
                                error_dob=true;
                                JOptionPane.showMessageDialog(null,"Choose Correct Birthday.");
                            }
                            String gender="0";                                                                          // default values of gender =0 , which means no gender has been selected.
                            if(RB_Female.isSelected())   {gender="F";GENDER="F";}
                            else if(RB_Male.isSelected()){gender="M";GENDER="M";}

                            if(error_dob==false)
                            {
                                boolean error1=false;     
                                                                                // To send mail of account created cum check the VALIDITY of EMAIl.
                                try{
                                    String FROM, FROMPASS, SUB, MAILMSG;
                                    String [] TO={NEWEMAIL};                    // user's EMAIL
                                    SUB="Your ASAPP account has succesfully created.";
                                    MAILMSG="Hey ! "+FNAME+" you're succesfully sign up for ASAPP. \n Welcome to the ASAPP Community.\n ASAPP is a "+
                                        "PC Messaging app, which connects you with your loved once in an easy way.\n"+
                                        " hope that you enjoy the application.\n\n"+
                                        "|| Feel free to ask and welcome for the feedback and suggestions.||\n"+
                                        "(You can send us on this address too, by reply.)\n\n"+
                                        " \t B H A R A T   S H R I V A S T A V A   P R O D U C T I O N   © 2017";
                                    Class_Mail.sendFromGMail( TO, SUB, MAILMSG);  // NewClass is a CLASS to send emails.

                                    }
                                catch(Exception e)
                                    {
                                        error1=true;
                                        JOptionPane.showMessageDialog(rootPane, "Something went wrong.Please Try again.");
                                    }
                        // BACK END WORK STARTs
                            if(!error1 && !Class_Mail.connection_error)
                                {
                                try{
                                    String DNAME=ChangeToValidTableName(NEWEMAIL);           // to convert email to Table name for use as sql
                                    Class.forName(Class_Setting.DRIVER_MANAGER);
                                    Connection con=DriverManager.getConnection(Class_Setting.URL+Class_Setting.DATABASE_NAME,Class_Setting.USERNAME,Class_Setting.PASSWORD);
                                    Statement stmt=con.createStatement();
                                    String query;
                                    boolean error2=false;   
                                                    // For user's profile
                                    try{ 
                                        query="create table profile_"+DNAME+" (email varchar(30) ," // create tabele of name PROFILE  
                                            + "pass varchar(20),name varchar(25), sname varchar(25),"
                                            + "Dob date,dname varchar(30),gender varchar(6),"
                                            + "image longblob, lastseen varchar(20),liked varchar(5));";
                                        stmt.executeUpdate(query);
                                                                                    /*      email - user EMAIL
                                                                                            pass  - user's PASSWORD
                                                                                            name  - user's FIRST NAME
                                                                                            sname - user's SUR NAME
                                                                                            Dob   - user's DOB
                                                                                            dname - user's TABLE NAME
                                                                                            gender - user's GENDER (M or F)
                                                                                            image - user PRO PIC
                                                                                            lastseen - last time LOGIN of user's
                                                                                            liked  -  did user liked asapp in feedback option.
                                                                                    */
                                        }
                                    catch(Exception er1)
                                        {   error2=true;                                 // if account already exist.
                                            JOptionPane.showMessageDialog(rootPane,"User already exist. \n"
                                                    + " Make sure you are connected with your Network connection");   
                                        }
                                    if(!error2)
                                        {

                                         query="create table chats_"+DNAME+"(FEMAIL varchar(30), FNAME varchar(15), SNAME varchar(30));";
                                         stmt.executeUpdate(query);
                                         query="Insert into profile_"+DNAME+" values('"+NEWEMAIL+"','"+NEWPASS+"','"+FNAME+"','"+SNAME+"',"+
                                               "'"+YEAR+"-"+MONTH+"-"+DAY+"','"+DNAME+"','"+gender+"',NULL,NULL,"+"'not'"+");";
                                                                                    // Inserts details in profile table
                                         if(stmt.executeUpdate(query)==1)
                                            { 
                                              JOptionPane.showMessageDialog(rootPane,"Account has Created. \n Now you can LogIn");
                                              new LogIn().setVisible(true);                               // page RELOAD
                                              JOptionPane.showMessageDialog(rootPane,"Welcome to asapp community.");
                                              dispose();
                                            }
                                        }
                                    }
                                catch(Exception er)
                                    {

                                        JOptionPane.showMessageDialog(rootPane,er.getMessage()+" Check the details and try again. \n "
                                                + "Make sure you are connected with your Network Connection.");
                                    }
                                }
                            }
                
                        // TASK END
                    SwingUtilities.invokeLater(new Runnable()
                                    {                                                               //do swing work on 
                                                                                                     // event dispatching thread  Abstract Window Toolkit 
                                        public void run()
                                        {
                                        d.dispose();
                                        }
                                    }                       );
                        }
                    };
                                t.start();
                                d.setVisible(true); 

                } // else section closed here.
      
    }//GEN-LAST:event_Button_createaccountActionPerformed
// pass PF
    private void PF_NewPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PF_NewPassFocusGained
      newpasslable.setVisible(false);    
    }//GEN-LAST:event_PF_NewPassFocusGained

    private void PF_NewPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PF_NewPassFocusLost
   PF_NewPass.setText(PF_NewPass.getText().trim());  
   if(PF_NewPass.getText().isEmpty())
    newpasslable.setVisible(true);
    }//GEN-LAST:event_PF_NewPassFocusLost
// To ensure that First name should be correct and Legal
    private void TF_FnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TF_FnameKeyTyped

char k=evt.getKeyChar();
if(k>='0' && k<='9')
    evt.consume();

    }//GEN-LAST:event_TF_FnameKeyTyped
// To ensure that surname or Last Name should be correct or Legal
    private void TF_SnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TF_SnameKeyTyped

char k=evt.getKeyChar();
if(k>='0' && k<='9')
    evt.consume();        
    }//GEN-LAST:event_TF_SnameKeyTyped
// To show password in TF
    private void jLabel17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MousePressed
   TF_ShowPass.setText(PF_NewPass.getText());
TF_ShowPass.setVisible(true); 
    }//GEN-LAST:event_jLabel17MousePressed

    private void jLabel17MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseReleased
TF_ShowPass.setVisible(false);        
    }//GEN-LAST:event_jLabel17MouseReleased

    private void Label_TandCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_TandCMouseClicked
        try{

                UIManager.put("OptionPane.minimumSize",new Dimension(100,30));
                JOptionPane.showMessageDialog(null,
                          "              Read All the terms carefully :- \n"
                        + "\n* asapp doesn't provide any security feature"
                        + "\n   for information provide by yourself. "
                        + "\n* asapp will not be responsible for any thread."
                        + "\n* There can be outages, data loss and security features"
                        + "\n   that do not meet the standards which you expect."
                        + "\n\n || asapp recommand you to use non-working password ||"
                        + ""
                        + "", "Terms and Conditions.", 
                        WIDTH, new ImageIcon("src\\images\\front_1.gif"));
        }catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
// TODO add your handling code here:
    }//GEN-LAST:event_Label_TandCMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aboutus_Button;
    private javax.swing.JButton Button_LogIn;
    private javax.swing.JButton Button_createaccount;
    private javax.swing.JLabel Help_Label;
    private javax.swing.JLabel Label_TandC;
    private javax.swing.JLabel Label_bigimg;
    private javax.swing.JLabel Label_ty;
    private javax.swing.JLabel Label_ty1;
    private javax.swing.JLabel Label_tyfor;
    private javax.swing.JLabel Label_wehope;
    private javax.swing.JPasswordField PF_LogIn_pass;
    private javax.swing.JPasswordField PF_NewPass;
    private javax.swing.JRadioButton RB_Female;
    private javax.swing.JRadioButton RB_Male;
    private javax.swing.JTextField TF_Fname;
    private javax.swing.JTextField TF_LogIn_Email;
    private javax.swing.JTextField TF_NewEmail;
    private javax.swing.JTextField TF_ReEmail;
    private javax.swing.JTextField TF_ShowPass;
    private javax.swing.JTextField TF_Sname;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox daycb;
    private javax.swing.JLabel e1;
    private javax.swing.JLabel e2;
    private javax.swing.JLabel e3;
    private javax.swing.JLabel e4;
    private javax.swing.JLabel e5;
    private javax.swing.JLabel e6;
    private javax.swing.JLabel fnamelable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox monthcb;
    private javax.swing.JLabel newemaillable;
    private javax.swing.JLabel newpasslable;
    private javax.swing.JLabel reemaillable;
    private javax.swing.JLabel snamelable;
    private javax.swing.JComboBox yearcb;
    // End of variables declaration//GEN-END:variables
}
